# Generated by Django 5.1.4 on 2024-12-26 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teachers_images/')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('telephone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('work_expert', models.PositiveIntegerField()),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='subjects.subject')),
            ],
        ),
    ]
